# Generated by Django 3.2.18 on 2023-03-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='category_title',
            field=models.CharField(blank=True, db_column='CategoryTitle', max_length=100, null=True),
        ),
    ]
