# Generated by Django 3.2.18 on 2023-03-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0013_auto_20211103_1023'),
        ('ticket', '0003_alter_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='insuree',
            field=models.ForeignKey(blank=True, db_column='InsureeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree'),
        ),
    ]
