# Generated by Django 3.2.16 on 2023-02-01 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0013_auto_20211103_1023'),
        ('grievance', '0003_auto_20221130_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='benficiary',
        ),
        migrations.AddField(
            model_name='grievance',
            name='grievance_code',
            field=models.CharField(db_column='grievanceCode', max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='insuree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='created_by',
            field=models.CharField(blank=True, db_column='createdBy', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('In Progress', 'In Progress')], db_column='Status', default='Open', max_length=36),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='type_of_grievance',
            field=models.CharField(choices=[('Inquiry', 'Inquiry'), ('Problem', 'Problem'), ('General', 'General')], db_column='typeOfGrievance', default='General', max_length=36),
        ),
    ]
