# Generated by Django 3.2.18 on 2023-08-11 13:14

from django.db import migrations

def add_initial_data(grievance, schema_editor):
    Category = grievance.get_model('grievance', 'Category')
    Category.objects.create(category_title='Claim', slug="C")
    # Add more data as needed

def reverse_add_initial_data(grievance, schema_editor):
    Category = grievance.get_model('grievance', 'Category')
    Category.objects.filter(category_title='Claim').delete()

class Migration(migrations.Migration):
    dependencies = [
        ('grievance', '0004_auto_20230425_1638'),
    ]

    operations = [
        migrations.RunPython(add_initial_data, reverse_code=reverse_add_initial_data),
    ]

