# Generated by Django 3.2.18 on 2023-03-09 13:08

import core.fields
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_insuree'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.UUIDField(blank=True, db_column='LegacyID', null=True)),
                ('filename', models.TextField(blank=True, max_length=1000, null=True)),
                ('mime_type', models.TextField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(blank=True, max_length=1000, null=True)),
                ('document', models.TextField(blank=True, null=True)),
                ('date', core.fields.DateField(blank=True, default=core.utils.TimeUtils.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachment', to='ticket.ticket')),
            ],
            options={
                'db_table': 'tblTicketAttachment',
                'managed': True,
            },
        ),
    ]
