# Generated by Django 3.2.18 on 2023-03-09 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticketattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateField(blank=True, db_column='Due_Date', null=True),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
