# Generated by Django 3.2.18 on 2023-03-09 15:43

import core.fields
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20230309_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='date',
            field=core.fields.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
