# Generated by Django 3.2.18 on 2023-03-10 00:11

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_last_login_on_interactive_user'),
        ('ticket', '0008_alter_ticketattachment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(db_column='TicketId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachment', to='ticket.ticket'),
        ),
        migrations.CreateModel(
            name='AttachmentMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachment', to='core.mutationlog')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='ticket.ticketattachment')),
            ],
            options={
                'db_table': 'ticket_AttachmentMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
    ]
