# Generated by Django 3.2.18 on 2023-03-17 16:30

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_add_enrollment_officer_gql_query_location_right'),
        ('ticket', '0009_auto_20230310_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='description',
            new_name='ticket_description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_of_incident',
            field=models.DateField(blank=True, db_column='Date_of_Incident', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_submitted',
            field=core.fields.DateField(blank=True, db_column='Date_Submission', default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.ForeignKey(blank=True, db_column='LocationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='location.location'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name_of_complainant',
            field=models.CharField(blank=True, db_column='Name of Complainanat', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone',
            field=models.IntegerField(blank=True, db_column='PhoneNumber', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution',
            field=models.CharField(blank=True, db_column='Resolution', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(blank=True, db_column='TicketCode', max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_dueDate',
            field=models.DateField(blank=True, db_column='Tciket_DueDate', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_priority',
            field=models.CharField(choices=[('C', 'Critical'), ('H', 'High'), ('N', 'Normal'), ('L', 'Low')], db_column='TicketPriority', default='N', help_text='how critical is the problem C = Critical and L = Low ', max_length=2),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.TextField(choices=[('W', 'Waiting'), ('T', 'Todo'), ('I', 'Inprogress'), ('R', 'Review'), ('C', 'CLOSE')], db_column='TicketStatus', default='W', max_length=2),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_title',
            field=models.CharField(blank=True, db_column='TicketTitle', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='witness',
            field=models.CharField(blank=True, db_column='Witness', max_length=255, null=True),
        ),
    ]
