# Generated by Django 3.2.18 on 2023-03-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20230317_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='location',
        ),
    ]
