# Generated by Django 3.2.16 on 2023-03-28 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_add_enrollment_officer_gql_query_location_right'),
        ('ticket', '0012_ticket_current_village'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='current_village',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_location',
            field=models.ForeignKey(blank=True, db_column='EventLocationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_location', to='location.location'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='insuree_location',
            field=models.ForeignKey(blank=True, db_column='insureeLocationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insuree_location', to='location.location'),
        ),
    ]
