# Generated by Django 3.2.16 on 2023-03-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_auto_20230328_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='insuree_location',
            field=models.CharField(blank=True, db_column='insureeLocation', max_length=50, null=True),
        ),
    ]
