# Generated by Django 3.2.16 on 2023-03-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_alter_ticket_insuree_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_priority',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'high'), ('Normal', 'Normal'), ('Low', 'Low')], db_column='TicketPriority', default='Normal', help_text='how critical is the problem C = Critical and L = Low ', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.TextField(choices=[('Waiting', 'Waiting'), ('Todo', 'Todo'), ('Inprogress', 'Inprogress'), ('Review', 'Review'), ('CLOSE', 'CLOSE')], db_column='TicketStatus', default='Waiting', max_length=15),
        ),
    ]
